[default]
src = 'src'
out = 'out'
libs = ['lib']
initial_balance = '0x4563918244f40000'

remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config